[project]
name = 'Blockchain-Based-Educational-Continuing-Education-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.course-verification]
path = 'contracts/course-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.professional-verification]
path = 'contracts/professional-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
